name: Build and Publish
on:
  push:
  schedule:
    - cron: 0 0 1/7 * *

env:
  GIT: 'true'
  GITURL: 'https://github.com/Sirherobrine23/APT_bysh23'
  GITBRANCH: master
  GITUSER: Sirherobrine23
  GITPASS: ${{ secrets.PASS }}
  GITDIR: 'package/main'
  UNISCRIPT: 'true'
  PRESCRIPT: 'script.sh'
  
jobs:
  Debian-Package:
    runs-on: ubuntu-18.04
    container: sirherobrine23/public-multi-debian-packages-copiler:latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
 
      - name: DPKG Build and Publish
        run: |
          init_23
